# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore")                     # ✅ ① 인증서/프로파일 가져오기

    increment_build_number(xcodeproj: "VannyVanny.xcodeproj")

    build_app(                                  # ✅ ② 빌드
      scheme: "VannyVanny",
      export_method: "app-store"
    )

    upload_to_testflight                        # ✅ ③ TestFlight 업로드
  end
end
