# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore", readonly: true)  # ← 이 줄만 바꿔도 해결 가능

    increment_build_number(xcodeproj: "VannyVanny.xcodeproj")

    build_app(
      scheme: "VannyVanny",
      export_method: "app-store"
    )

    upload_to_testflight
  end
end
