# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do

    get_certificates
    get_provisioning_profile

    increment_build_number(xcodeproj: "VannyVanny.xcodeproj")

    build_app(                                  # ✅ ② 빌드
      scheme: "VannyVanny",
      export_method: "app-store",
      export_options: {
          provisioningProfiles: { 
# ✅ apple developer 에서 provisioning profile 의 이름을 입력해주어야 한다.
              "com.appleAcademy.VannyVanny" => "match AppStore com.appleAcademy.VannyVanny"
          }
      }
    )

    upload_to_testflight(
      # ✅ api_key_path 를 지정해주는 대신 api_key 를 만들어서 작성할 수 있다.
          #  api_key: api_key,
          api_key_path: "fastlane/key.json"
          )
  end
end
